"""gifs table

Revision ID: 2733ccc3cec8
Revises: 
Create Date: 2019-12-13 18:55:56.308276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2733ccc3cec8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gif',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.DateTime(), nullable=True),
    sa.Column('filesize', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gif_filesize'), 'gif', ['filesize'], unique=False)
    op.create_index(op.f('ix_gif_name'), 'gif', ['name'], unique=True)
    op.create_index(op.f('ix_gif_path'), 'gif', ['path'], unique=True)
    op.create_index(op.f('ix_gif_timestamp'), 'gif', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gif_timestamp'), table_name='gif')
    op.drop_index(op.f('ix_gif_path'), table_name='gif')
    op.drop_index(op.f('ix_gif_name'), table_name='gif')
    op.drop_index(op.f('ix_gif_filesize'), table_name='gif')
    op.drop_table('gif')
    # ### end Alembic commands ###
