"""gifs thumb_path

Revision ID: 40fd4a7beffe
Revises: 8c53b170a46c
Create Date: 2019-12-20 13:28:58.518513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40fd4a7beffe'
down_revision = '8c53b170a46c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gif', sa.Column('thumb_path', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_gif_thumb_path'), 'gif', ['thumb_path'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gif_thumb_path'), table_name='gif')
    op.drop_column('gif', 'thumb_path')
    # ### end Alembic commands ###
