"""settings float

Revision ID: 8c53b170a46c
Revises: 9664bcd439bb
Create Date: 2019-12-16 08:10:15.107329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c53b170a46c'
down_revision = '9664bcd439bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_settings_play_length'), 'settings', ['play_length'], unique=False)
    op.create_index(op.f('ix_settings_shuffle'), 'settings', ['shuffle'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_shuffle'), table_name='settings')
    op.drop_index(op.f('ix_settings_play_length'), table_name='settings')
    # ### end Alembic commands ###
