"""settings table

Revision ID: 9664bcd439bb
Revises: fd40889c16bd
Create Date: 2019-12-16 07:59:42.073369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9664bcd439bb'
down_revision = 'fd40889c16bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('play_length', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('shuffle', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
